# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
  branches:
    include:
    - main
    - refs/tags/*
    - releases/tags/*
    - azure-pipeline

pr:
- main
- azure-pipeline

variables:
- name: isMainBranch
  value: $[eq(variables['build.sourceBranch'], 'refs/heads/master')]
- name: isTagRelease
  value: $[startsWith(variables['build.sourceBranch'], 'refs/tags/v')]
- name: dockerImageName
  value: nicoandra/s3-browser


pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: "Show variables"
    jobs:
    - job: "Show variables"
      steps:
      - bash: |
        echo "isMainBranch: $(variables.isMainBranch)"
        echo "isTagRelease: $(variables.isTagRelease)"
        echo "dockerImageName: $(variables.dockerImageName)"
  - stage: 'InstallOS'
    jobs:
    - job: "InstallOS"
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
  - stage: 'BuildFrontEnd'
    jobs:
    - template: '.pipeline/job_check_changes.yml'
      parameters:
        path: 'frontend/'
    - template: '.pipeline/job_enforce_standards.yml'
      parameters:
        path: 'frontend/'
  - stage: 'BuildBackEnd'
    jobs:
    - template: '.pipeline/job_check_changes.yml'
      parameters:
        path: 'backend/'
    - template: '.pipeline/job_enforce_standards.yml'
      parameters:
        path: 'frontend/'    
  - stage: 'DockerBuildAndPush'
    jobs:
    - job: RefTags
      condition: or(eq(variables.isMainBranch, true), eq(variables.isTagRelease, true))
      steps:
      - bash: |
          echo Building Docker Image for tag "$(build.sourceBranchName)"
      - task: Docker@2
        displayName: Login to DockerHub
        inputs:
          command: login
          containerRegistry: "NicoAndra DockerHub"
      - task: Docker@2
        displayName: Build
        inputs:
          command: build
          tags: |
            $(build.sourceBranchName)
      - task: Docker@2
        displayName: Push Tag
        condition: eq(variables.isTagRelease, true)
        inputs:
          command: push
          repository: $(variables.dockerImageName)
          tags: |
            $(build.sourceBranchName)
      - task: Docker@2
        displayName: Push Latest
        condition: eq(variables.isMainBranch, true)
        inputs:
          command: push
          repository: $(variables.dockerImageName)
          tags: |
            latest
      - task: Docker@2
        displayName: Logout from DockerHub
        inputs:
          command: logout
          containerRegistry: "NicoAndra DockerHub"
