# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- main  

pr:
- main
- azure-pipeline

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'InstallOS'
    jobs:
    - job: "InstallOS"
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
  - stage: 'BuildFrontEnd'
    jobs:
    - template: '.pipeline/job_check_changes.yml'
      parameters:
        path: 'frontend/'
    - template: '.pipeline/job_npm_install.yml'
      parameters:
        path: 'frontend/'
      dependsOn: CheckChanges # <- Important: Mark previous job as dependency        
      condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
  - stage: 'BuildBackEnd'
    jobs:
      - template: '.pipeline/job_check_changes.yml'
        parameters:
          path: 'backend/'
      - template: '.pipeline/job_npm_install.yml'
        parameters:
          path: 'backend/'
        dependsOn: CheckChanges # <- Important: Mark previous job as dependency        
        condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
        