# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- main  

pr:
- main
- azure-pipeline

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'InstallOS'
    jobs:
    - job: "InstallOS"
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
  - stage: 'BuildFrontEnd'
    jobs:
    - template: '.pipeline/job_check_changes.yml'
      parameters:
        path: 'frontend/'
    - job: Build       
      displayName: 'Only when source code changed'    
      dependsOn: CheckChanges # <- Important: Mark previous job as dependency        
      condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
      steps:
      - script: |
          cd frontend
          npm install
          npm run test
          echo "Build Success!"
        displayName: 'FrontEnd - Install and Build'
  - stage: 'BuildBackEnd'
    jobs:
    - template: '.pipeline/job_checkchanges.yml'
      parameters:
        path: 'backend/'
    - job: Build       
      displayName: 'Only when source code changed'    
      dependsOn: CheckChanges # <- Important: Mark previous job as dependency        
      condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
      steps:
      - script: |
          cd backend
          echo "Build Success!"
        displayName: 'Backend - Install and Build'        
