version: "3.6"

services:

  backend:
    build:
      context: backend
      target: development
    ports:
      - 3000:3000
      - 9229:9229 # For NodeJs Debugger
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    command: npm run start:debug
    env_file:
      - .env


  app-test-watch:
    build:
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    command: npm run test:watch
    env_file:
      - .env    

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 5000:3000
      - 9230:9229 # For NodeJs Debugger
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    command: npm start
    env_file:
      - .env    
    depends_on:
      - backend
    
