parameters:
  path: ''

jobs:
- job: EnforceStandards
  displayName: 'Enforce standards'
  dependsOn: CheckChanges
  condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
  steps:
  - bash: |
      echo "Preparing ${{ parameters.path }}"
      cd ${{ parameters.path }}
      npm install
      npm run lint:check
      CI=true npm run test
    name: EnforceStandards
    displayName: 'Enforce standards'
  - bash: |
      CI=true npm run test:cov
    name: CodeCoverage
    displayName: 'Code Coverage'


