parameters:
  path: ''

jobs:
- job: EnforceStandards
  displayName: 'Enforce standards'
  dependsOn: CheckChanges
  condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
  steps:
  - bash: |
      cd ${{ parameters.path }}
      npm install
    name: NPMInstall
    displayName: 'NPM Install'
  - bash: |
      cd ${{ parameters.path }}
      npm run lint:check
    name: Linter
    displayName: 'Linter'
  - bash: |
      cd ${{ parameters.path }}
      CI=true npm run test
    name: Tests
    displayName: 'Run Test Suite'
  # - bash: |
  #    cd ${{ parameters.path }}
  #    CI=true npm run test:cov
  #  name: CodeCoverage
  #  displayName: 'Code Coverage'


