parameters:
  path: ''

jobs:
- job: EnforceStandards
  displayName: 'Enforce standards'
  dependsOn: CheckChanges
  condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
  steps:
  - name: EnforceStandards
    displayName: 'Enforce standards'
    bash: |
      echo "Preparing ${{ parameters.path }}"
      cd ${{ parameters.path }}
      npm install
      npm run lint:check
      npm run test
  - name: CodeCoverage
    displayName: 'Code Coverage'
    bash: |
      npm run test:cov

